"""Кроссплатформенное управление подключением Booster к MCP-клиентам."""

from __future__ import annotations

import importlib.util
import json
import os
import shlex
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Any, cast

from repository_scanner import ARTIFACTS_DIRECTORY, SCAN_CONFIG_FILENAME, ScanConfig

LAUNCHER_MARKER = "Generated by Booster Control"
SUPPORTED_CLIENTS = ("vscode", "claude")
SUPPORTED_SCOPES = ("workspace", "user")


class ControlError(RuntimeError):
    """Понятная пользователю ошибка при изменении конфигурации клиента."""


@dataclass(frozen=True)
class ConnectionTarget:
    """Расположение и схема конфигурации конкретного MCP-клиента."""

    client: str
    scope: str
    config_path: Path
    servers_key: str
    default_name: str


def resolve_project(path: str | Path) -> Path:
    """Возвращает существующий каталог репозитория в абсолютном виде."""
    project = Path(path).expanduser().resolve()
    if not project.is_dir():
        raise ControlError(f"Repository directory does not exist: {project}")
    return project


def runtime_info() -> dict[str, str]:
    """Возвращает исполняемый Python и server.py текущей установки Booster."""
    installation = Path(__file__).resolve().parent
    server_path = installation / "server.py"
    python_path = Path(sys.executable).resolve()
    if server_path.is_file():
        candidates = (
            installation / ".venv" / "Scripts" / "python.exe",
            installation / ".venv" / "bin" / "python",
        )
        python_path = next(
            (candidate.resolve() for candidate in candidates if candidate.is_file()),
            python_path,
        )
    return {
        "python": str(python_path),
        "server": str(server_path),
        "installation": str(installation),
    }


def _platform_name(platform_name: str | None = None) -> str:
    return (platform_name or sys.platform).lower()


def _user_home(home: Path | None = None) -> Path:
    return (home or Path.home()).expanduser().resolve()


def vscode_user_config_path(
    home: Path | None = None,
    platform_name: str | None = None,
) -> Path:
    """Находит стандартный user-level mcp.json VS Code для текущей ОС."""
    user_home = _user_home(home)
    system = _platform_name(platform_name)
    if system.startswith("win"):
        app_data = (
            Path(os.environ["APPDATA"])
            if home is None and os.environ.get("APPDATA")
            else user_home / "AppData" / "Roaming"
        )
        return app_data / "Code" / "User" / "mcp.json"
    if system == "darwin":
        return user_home / "Library" / "Application Support" / "Code" / "User" / "mcp.json"
    return user_home / ".config" / "Code" / "User" / "mcp.json"


def claude_user_config_path(
    home: Path | None = None,
    platform_name: str | None = None,
) -> Path:
    """Находит стандартный user-level файл Claude Desktop для текущей ОС."""
    user_home = _user_home(home)
    system = _platform_name(platform_name)
    if system.startswith("win"):
        app_data = (
            Path(os.environ["APPDATA"])
            if home is None and os.environ.get("APPDATA")
            else user_home / "AppData" / "Roaming"
        )
        return app_data / "Claude" / "claude_desktop_config.json"
    if system == "darwin":
        return (
            user_home / "Library" / "Application Support" / "Claude" / "claude_desktop_config.json"
        )
    return user_home / ".config" / "Claude" / "claude_desktop_config.json"


def resolve_connection_target(
    client: str,
    scope: str,
    project: str | Path,
    *,
    home: Path | None = None,
    platform_name: str | None = None,
) -> ConnectionTarget:
    """Возвращает клиентский конфиг, совместимый с выбранной областью."""
    normalized_client = client.lower()
    normalized_scope = scope.lower()
    if normalized_client not in SUPPORTED_CLIENTS:
        available = ", ".join(SUPPORTED_CLIENTS)
        raise ControlError(f"Unsupported client '{client}'. Available clients: {available}.")
    if normalized_scope not in SUPPORTED_SCOPES:
        available = ", ".join(SUPPORTED_SCOPES)
        raise ControlError(f"Unsupported scope '{scope}'. Available scopes: {available}.")

    project_path = resolve_project(project)
    if normalized_client == "vscode":
        if normalized_scope == "workspace":
            return ConnectionTarget(
                client="vscode",
                scope="workspace",
                config_path=project_path / ".vscode" / "mcp.json",
                servers_key="servers",
                default_name="boosterLocal",
            )
        return ConnectionTarget(
            client="vscode",
            scope="user",
            config_path=vscode_user_config_path(home, platform_name),
            servers_key="servers",
            default_name="Booster",
        )

    if normalized_scope != "user":
        raise ControlError("Claude Desktop supports only the user scope.")
    return ConnectionTarget(
        client="claude",
        scope="user",
        config_path=claude_user_config_path(home, platform_name),
        servers_key="mcpServers",
        default_name="Booster",
    )


def _read_json_object(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        value: object = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise ControlError(
            f"Cannot update {path}: it is not valid JSON. Booster made no changes."
        ) from exc
    except OSError as exc:
        raise ControlError(f"Cannot read {path}: {exc}") from exc
    if not isinstance(value, dict):
        raise ControlError(f"Cannot update {path}: the root JSON value must be an object.")
    return cast(dict[str, Any], value)


def _atomic_write_json(path: Path, value: dict[str, Any]) -> Path | None:
    """Пишет JSON атомарно и сохраняет исходный файл перед изменением."""
    original = path.read_bytes() if path.exists() else None
    path.parent.mkdir(parents=True, exist_ok=True)
    backup_path = None
    if original is not None:
        backup_path = path.with_name(f"{path.name}.booster.bak")
        backup_path.write_bytes(original)

    file_descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
    )
    temporary_path = Path(temporary_name)
    try:
        with os.fdopen(file_descriptor, "w", encoding="utf-8", newline="\n") as stream:
            json.dump(value, stream, ensure_ascii=False, indent=2)
            stream.write("\n")
        os.replace(temporary_path, path)
    except OSError as exc:
        temporary_path.unlink(missing_ok=True)
        raise ControlError(f"Cannot write {path}: {exc}") from exc
    return backup_path


def _server_store(config: dict[str, Any], target: ConnectionTarget) -> dict[str, Any]:
    servers: object = config.setdefault(target.servers_key, {})
    if not isinstance(servers, dict):
        raise ControlError(
            f"Cannot update {target.config_path}: '{target.servers_key}' must be an object."
        )
    return cast(dict[str, Any], servers)


def build_server_definition(
    client: str,
    project: str | Path | None,
    *,
    bind_repository: bool = True,
) -> dict[str, Any]:
    """Строит переносимую stdio-конфигурацию из текущей установки Booster."""
    runtime = runtime_info()
    server = Path(runtime["server"])
    if not server.is_file():
        raise ControlError(f"Booster server entry point was not found: {server}")

    if bind_repository:
        if project is None:
            raise ControlError("A repository is required when binding REPOS.")
        working_directory = resolve_project(project)
    else:
        working_directory = Path(runtime["installation"])

    definition: dict[str, Any] = {
        "command": runtime["python"],
        "args": [runtime["server"]],
        "cwd": str(working_directory),
        "env": {"CITY_PORT": "0"},
    }
    if bind_repository:
        definition["env"]["REPOS"] = str(working_directory)
    if client.lower() == "vscode":
        definition["type"] = "stdio"
    return definition


def connect(
    client: str,
    scope: str,
    project: str | Path,
    *,
    name: str | None = None,
    force: bool = False,
    bind_repository: bool | None = None,
    home: Path | None = None,
    platform_name: str | None = None,
) -> dict[str, Any]:
    """Регистрирует текущую установку Booster в выбранном MCP-клиенте."""
    target = resolve_connection_target(
        client, scope, project, home=home, platform_name=platform_name
    )
    server_name = name or target.default_name
    config = _read_json_object(target.config_path)
    servers = _server_store(config, target)
    should_bind_repository = (
        target.scope == "workspace" if bind_repository is None else bind_repository
    )
    definition = build_server_definition(
        target.client,
        project,
        bind_repository=should_bind_repository,
    )
    existing = servers.get(server_name)
    if existing == definition:
        return {
            "updated": False,
            "reason": "already_configured",
            "client": target.client,
            "scope": target.scope,
            "server_name": server_name,
            "config_path": str(target.config_path),
            "backup_path": None,
            "repository_bound": should_bind_repository,
        }
    if existing is not None and not force:
        raise ControlError(
            f"Server '{server_name}' already exists in {target.config_path}. "
            "Use --force to replace only this entry."
        )

    servers[server_name] = definition
    backup_path = _atomic_write_json(target.config_path, config)
    return {
        "updated": True,
        "client": target.client,
        "scope": target.scope,
        "server_name": server_name,
        "config_path": str(target.config_path),
        "backup_path": str(backup_path) if backup_path else None,
        "repository_bound": should_bind_repository,
        "definition": definition,
    }


def disconnect(
    client: str,
    scope: str,
    project: str | Path,
    *,
    name: str | None = None,
    home: Path | None = None,
    platform_name: str | None = None,
) -> dict[str, Any]:
    """Удаляет только указанную запись Booster из конфигурации MCP-клиента."""
    target = resolve_connection_target(
        client, scope, project, home=home, platform_name=platform_name
    )
    server_name = name or target.default_name
    if not target.config_path.exists():
        return {
            "updated": False,
            "reason": "config_not_found",
            "client": target.client,
            "scope": target.scope,
            "server_name": server_name,
            "config_path": str(target.config_path),
        }

    config = _read_json_object(target.config_path)
    servers = _server_store(config, target)
    if server_name not in servers:
        return {
            "updated": False,
            "reason": "server_not_found",
            "client": target.client,
            "scope": target.scope,
            "server_name": server_name,
            "config_path": str(target.config_path),
        }

    del servers[server_name]
    backup_path = _atomic_write_json(target.config_path, config)
    return {
        "updated": True,
        "client": target.client,
        "scope": target.scope,
        "server_name": server_name,
        "config_path": str(target.config_path),
        "backup_path": str(backup_path) if backup_path else None,
    }


def connection_status(
    client: str,
    scope: str,
    project: str | Path,
    *,
    name: str | None = None,
    home: Path | None = None,
    platform_name: str | None = None,
) -> dict[str, Any]:
    """Возвращает состояние записи Booster без изменения конфигурации."""
    target = resolve_connection_target(
        client, scope, project, home=home, platform_name=platform_name
    )
    server_name = name or target.default_name
    result: dict[str, Any] = {
        "client": target.client,
        "scope": target.scope,
        "server_name": server_name,
        "config_path": str(target.config_path),
        "config_exists": target.config_path.is_file(),
        "configured": False,
    }
    if not target.config_path.is_file():
        return result
    try:
        config = _read_json_object(target.config_path)
        servers = _server_store(config, target)
    except ControlError as exc:
        result["valid"] = False
        result["error"] = str(exc)
        return result

    definition = servers.get(server_name)
    result["valid"] = True
    result["configured"] = definition is not None
    if isinstance(definition, dict):
        server_definition = cast(dict[str, Any], definition)
        result["command"] = server_definition.get("command")
        result["server"] = (server_definition.get("args") or [None])[0]
        environment = server_definition.get("env")
        result["repository_bound"] = isinstance(environment, dict) and bool(
            cast(dict[str, Any], environment).get("REPOS")
        )
    return result


def scan_settings(project: str | Path) -> dict[str, Any]:
    """Возвращает сохранённые scan-настройки либо активный профиль по умолчанию."""
    project_path = resolve_project(project)
    config_path = project_path / ARTIFACTS_DIRECTORY / SCAN_CONFIG_FILENAME
    config = ScanConfig.load(project_path)
    return {
        "config_path": str(config_path),
        "saved": config_path.is_file(),
        **config.to_dict(),
    }


def update_scan_settings(
    project: str | Path,
    *,
    profile: str | None = None,
    include_dependencies: bool | None = None,
    max_depth: int | None = None,
    max_files: int | None = None,
    max_file_bytes: int | None = None,
    max_total_bytes: int | None = None,
    max_directories: int | None = None,
) -> dict[str, Any]:
    """Сохраняет bounded scan policy, используемую CLI и MCP индексатором."""
    project_path = resolve_project(project)
    config = ScanConfig.for_profile(profile) if profile else ScanConfig.load(project_path)
    config = config.with_overrides(
        include_dependencies=include_dependencies,
        max_depth=max_depth,
        max_files=max_files,
        max_file_bytes=max_file_bytes,
        max_total_bytes=max_total_bytes,
        max_directories=max_directories,
    )
    config_path = config.save(project_path)
    return {"config_path": str(config_path), **config.to_dict()}


def artifact_status(project: str | Path) -> dict[str, dict[str, Any]]:
    """Показывает наличие артефактов без запуска индексации."""
    project_path = resolve_project(project)
    artifact_dir = project_path / ARTIFACTS_DIRECTORY
    result: dict[str, dict[str, Any]] = {}
    for name in ("repo_map.md", "code_city.html", "scan_config.json", "scan_report.json"):
        path = artifact_dir / name
        result[name] = {
            "path": str(path),
            "exists": path.is_file(),
            "size_bytes": path.stat().st_size if path.is_file() else 0,
        }
    return result


def doctor(project: str | Path) -> dict[str, Any]:
    """Выполняет быстрые локальные проверки запуска без изменения файлов."""
    project_path = resolve_project(project)
    runtime = runtime_info()
    packages = ("fastmcp", "mcp", "rank_bm25", "faiss", "sentence_transformers")
    checks: list[dict[str, object]] = [
        {"name": "python", "ok": Path(runtime["python"]).is_file(), "value": runtime["python"]},
        {"name": "server", "ok": Path(runtime["server"]).is_file(), "value": runtime["server"]},
    ]
    checks.extend(
        {
            "name": package,
            "ok": importlib.util.find_spec(package) is not None,
            "value": package,
        }
        for package in packages
    )
    return {
        "ok": all(check["ok"] is True for check in checks),
        "repository": str(project_path),
        "checks": checks,
        "artifacts": artifact_status(project_path),
    }


def user_bin_path(
    home: Path | None = None,
    platform_name: str | None = None,
) -> Path:
    """Возвращает переносимый пользовательский каталог для launcher-команд."""
    del platform_name
    return _user_home(home) / ".local" / "bin"


def launcher_path(
    home: Path | None = None,
    platform_name: str | None = None,
) -> Path:
    """Возвращает путь команды `booster` для целевой ОС."""
    filename = "booster.cmd" if _platform_name(platform_name).startswith("win") else "booster"
    return user_bin_path(home, platform_name) / filename


def _launcher_content(platform_name: str | None = None) -> str:
    python_path = str(Path(sys.executable).resolve())
    if _platform_name(platform_name).startswith("win"):
        return f'@echo off\r\nREM {LAUNCHER_MARKER}\r\n"{python_path}" -m cli %*\r\n'
    return (
        "#!/usr/bin/env sh\n"
        f"# {LAUNCHER_MARKER}\n"
        f'exec {shlex.quote(python_path)} -m cli "$@"\n'
    )


def install_launcher(
    *,
    home: Path | None = None,
    platform_name: str | None = None,
    force: bool = False,
) -> dict[str, Any]:
    """Устанавливает или обновляет безопасный launcher `booster` в ~/.local/bin."""
    path = launcher_path(home, platform_name)
    content = _launcher_content(platform_name)
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        existing = path.read_text(encoding="utf-8")
        if existing == content:
            return {
                "updated": False,
                "reason": "already_current",
                "launcher_path": str(path),
                "user_bin": str(path.parent),
            }
        if LAUNCHER_MARKER not in existing and not force:
            raise ControlError(
                f"Refusing to replace existing launcher: {path}. Use --force to replace it."
            )

    path.write_text(content, encoding="utf-8", newline="\n")
    if not _platform_name(platform_name).startswith("win"):
        path.chmod(path.stat().st_mode | 0o111)
    path_on_environment = any(
        Path(entry).expanduser().resolve() == path.parent.resolve()
        for entry in os.environ.get("PATH", "").split(os.pathsep)
        if entry
    )
    return {
        "updated": True,
        "launcher_path": str(path),
        "user_bin": str(path.parent),
        "path_on_environment": path_on_environment,
    }
